version: "3.7"

services:
  item-app:
    image: umarazis/item-app:v1 # Menggunakan image item-app dari Docker Hub
    depends_on:
      - item-db # Pastikan item-app hanya berjalan setelah item-db diluncurkan
    ports:
      - 80:8080 # Melakukan port mapping agar dapat diakses dari port 80 di host
    restart: always # Menerapkan restart policy agar container selalu restart ketika terhenti
  item-db:
    image: mongo:3 # Menggunakan image mongo:3 dari Docker Hub
    volumes:
      - app-db:/data/db # Memakai volume bernama app-db dengan target /data/db di container
    restart: always # Menerapkan restart policy agar container selalu restart ketika terhenti
volumes:
  app-db: